services:
  scrapyd:
    container_name: crawler
    build:
      context: ./crawler
      dockerfile: Dockerfile
    ports:
      - "6800:6800"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/app/data
    restart: unless-stopped
