# Generated by Django 5.1.1 on 2024-10-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='topic_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
