# Generated by Django 5.1.1 on 2024-10-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_jobs_topic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'managed': False},
        ),
    ]
