name: Deploy to server
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_IP}} << 'EOF'
            cd /home/${{secrets.SERVER_USERNAME}}/projects/kraven

            # Pull latest changes from the repo
            git pull origin main

            # Stop running containers
            docker-compose down

            # Rebuild and start services
            docker-compose up --build -d
          EOF
